// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolManagementInfrastructure.EF;

#nullable disable

namespace SchoolManagementInfrastructure.Migrations
{
    [DbContext(typeof(SchoolManagementContext))]
    [Migration("20251120095131_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFClassEFStudent", b =>
                {
                    b.Property<Guid>("ClassesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentsId")
                        .HasColumnType("uuid");

                    b.HasKey("ClassesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("EFClassEFStudent");
                });

            modelBuilder.Entity("EFStudentEFSubject", b =>
                {
                    b.Property<Guid>("StudentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectsId")
                        .HasColumnType("uuid");

                    b.HasKey("StudentsId", "SubjectsId");

                    b.HasIndex("SubjectsId");

                    b.ToTable("EFStudentEFSubject");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFBaseSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("BaseSubjects");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EFTeacherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("EFTeacherId");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFClassExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ClassExams");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFClassStudent", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.HasKey("StudentId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassStudents");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFClassTeacher", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.HasKey("TeacherId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("EFClassTeacher");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFExamImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamImages");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFIndividualExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseExamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaseExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("IndividualExams");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseSubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaseSubjectId");

                    b.HasIndex("ClassId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFSubjectStudent", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("SubjectId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("SubjectStudents");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("EFClassEFStudent", b =>
                {
                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFClass", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFStudent", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFStudentEFSubject", b =>
                {
                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFStudent", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFSubject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFClass", b =>
                {
                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFTeacher", null)
                        .WithMany("Classes")
                        .HasForeignKey("EFTeacherId");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFClassExam", b =>
                {
                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFClass", "Class")
                        .WithMany("ClassExams")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFSubject", "Subject")
                        .WithMany("ClassExams")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFClassStudent", b =>
                {
                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFClass", "Class")
                        .WithMany("ClassStudents")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFStudent", "Student")
                        .WithMany("ClassStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFClassTeacher", b =>
                {
                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFClass", "Class")
                        .WithMany("ClassTeachers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFTeacher", "Teacher")
                        .WithMany("ClassTeachers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFExamImage", b =>
                {
                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFIndividualExam", "Exam")
                        .WithMany("Images")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFIndividualExam", b =>
                {
                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFClassExam", "BaseExam")
                        .WithMany("IndividualExams")
                        .HasForeignKey("BaseExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFStudent", "Student")
                        .WithMany("IndividualExams")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseExam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFSubject", b =>
                {
                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFBaseSubject", "BaseSubject")
                        .WithMany("Subjects")
                        .HasForeignKey("BaseSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFClass", "Class")
                        .WithMany("Subjects")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFTeacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseSubject");

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFSubjectStudent", b =>
                {
                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFStudent", "Student")
                        .WithMany("SubjectStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolManagementInfrastructure.EF.Models.EFSubject", "Subject")
                        .WithMany("SubjectStudents")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFBaseSubject", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFClass", b =>
                {
                    b.Navigation("ClassExams");

                    b.Navigation("ClassStudents");

                    b.Navigation("ClassTeachers");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFClassExam", b =>
                {
                    b.Navigation("IndividualExams");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFIndividualExam", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFStudent", b =>
                {
                    b.Navigation("ClassStudents");

                    b.Navigation("IndividualExams");

                    b.Navigation("SubjectStudents");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFSubject", b =>
                {
                    b.Navigation("ClassExams");

                    b.Navigation("SubjectStudents");
                });

            modelBuilder.Entity("SchoolManagementInfrastructure.EF.Models.EFTeacher", b =>
                {
                    b.Navigation("ClassTeachers");

                    b.Navigation("Classes");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
